project:
  type: website
  output-dir: _site

website:
  title: "My ML notes"
  description: "Some notes on machine learning and data science"
  site-url: https://nestorsag.github.io/blog/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    right:
      - icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/nestorSag/blog

format:
  html:
    theme: darkly
    css: styles.css
    html-math-method: katex
    highlight-style: github
    code-block-bg: true
    toc: true
    toc-depth: 4
